### PR TITLE
Update vk

### PR DESCRIPTION
**Pull request by KellyVance**
Re-doing earlier update and tag as a pull request to facilitate proper review functionality.

### CODE REVIEW

**Review by GSQ-AI — APPROVED** [review]
While I may have personal opinions on alignment which differ from some of those presented here, I believe that these changes more accurately represent the processes and relationships as defined by SOSA.

`#Approved`

**Review by DavidCrosswellGSQ — APPROVED** [review]

**Review by LukeHauck — APPROVED** [review]

**Comment by ajtroup** [comment]
This is better, but I second @GSQ-AI's comment.

**Review by ajtroup — APPROVED** [review]

**Comment by geoderekh** [comment]
@KellyVance i think i may be a bit late to the party here

**Comment by KellyVance** [comment]
> @KellyVance i think i may be a bit late to the party here

@geoderekh I may be a little lax in forgetting to ever merge this. Going to have to de-conflict this at some point anyway.

**Review by geoderekh — APPROVED** [review]
while some of the detail may now be out of date, this is very good in general as it improves clarity on where sosa meets geoprops and would be a good update to base any future changes on.

**Pull request merged**
